### ISSUE TITLE
ModuleNotFoundError: No module named 'Crypto'

### ISSUE THREAD

**Issue by RiteshSec** [Denzerson1/ChromeStealer#1]
I have installed the Crypto Library using `pip install Crypto`. 

<img width="788" alt="image" src="https://github.com/Denzerson1/ChromeStealer/assets/110530131/93069cc9-a89f-4dc0-9e0a-ccf26a7494c6">

But Even then Getting the Below Error.

<img width="441" alt="image" src="https://github.com/Denzerson1/ChromeStealer/assets/110530131/e69593a4-893d-4995-b94a-e9f5bd5b1802">

What could be the reason and how to solve it?

Using Windows 11 with Python 3.11.4

**Comment by Denzerson1** [comment]
try cryptodome install, it is more up to date.

**Comment by RiteshSec** [comment]
Just Adding to this 

Before install cryptodome we also need to uninstall the existing Crypto, pycryto as all of these three packages get installed to the same folder, named Crypto. Installing different packages under the same folder name can be a common source for errors!. [Ref](https://stackoverflow.com/questions/19623267/importerror-no-module-named-crypto-cipher)

```
pip3 uninstall crypto 
pip3 uninstall pycrypto 
pip3 install pycryptodome
```
